# Generated by Django 5.2.8 on 2026-01-12 15:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
