# Generated by Django 5.2.8 on 2026-01-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_meal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='menu_pics'),
        ),
    ]
