# Generated by Django 5.2.8 on 2026-01-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_meal_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourorder',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
