# Generated by Django 5.2.8 on 2026-01-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_yourorder_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
